"""empty message

Revision ID: c95efee7e050
Revises: bd06d388c242
Create Date: 2025-05-06 07:42:13.511114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95efee7e050'
down_revision = 'bd06d388c242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('mass')
        batch_op.drop_column('homeworld')
        batch_op.drop_column('gender')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('url')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('gravity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('homeworld', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mass', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
